### ISSUE TITLE
Relax peerDependency requirements

### ISSUE THREAD

**Issue by fiznool** [codewareio/ngrx-store-freeze#9]
Currently this lib has a peerDependency on `"@angular/core": "^2.4.0"`. This causes peerDependency warnings when using this library with the Ionic framework, which currently uses Angular 2.2.1.

Is there a possibility this peerDependency could be relaxed? Or, is there even a need for this peerDependency at all? AFAICT the only peerDependency this library seems to need is `@ngrx/store`.

**Comment by tsm91** [comment]
@fiznool removed `"@angular/core": "^2.4.0"` and published `v0.1.7`

sry for the delay

**Comment by fiznool** [comment]
Thanks!
